# Generated by Django 3.2.8 on 2022-03-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_materia', models.CharField(max_length=255, unique=True)),
                ('qtd_aulas', models.IntegerField()),
                ('professor', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
