# Generated by Django 3.2.8 on 2022-03-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermaterias',
            name='professor',
        ),
    ]
