# Generated by Django 3.2.8 on 2022-03-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_registermaterias_professores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermaterias',
            old_name='professores',
            new_name='professor',
        ),
    ]
