# Generated by Django 3.2.8 on 2022-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_rename_professores_registermaterias_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermaterias',
            name='professor',
        ),
        migrations.AddField(
            model_name='registermaterias',
            name='professor',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
