# Generated by Django 3.2.8 on 2022-03-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_remove_cadastrarprofessores_materias'),
        ('materias', '0004_auto_20220302_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermaterias',
            name='professor',
        ),
        migrations.AddField(
            model_name='registermaterias',
            name='professor',
            field=models.ManyToManyField(related_name='materias', to='professores.CadastrarProfessores'),
        ),
    ]
