# Generated by Django 3.2.8 on 2022-03-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrarprofessores',
            name='materias',
        ),
    ]
