# Generated by Django 3.2.8 on 2022-03-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTurmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_turma', models.CharField(max_length=255, unique=True)),
                ('turno', models.CharField(max_length=255)),
                ('materias', models.ManyToManyField(related_name='turmas', to='materias.RegisterMaterias')),
            ],
        ),
    ]
