# Generated by Django 3.2.8 on 2022-02-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerturmas',
            name='materias',
        ),
        migrations.AddField(
            model_name='registerturmas',
            name='professores',
            field=models.ManyToManyField(related_name='turmas', to='professores.CadastrarProfessores'),
        ),
    ]
